version: "3.8"
services:
  database:
    image: docker.io/pbbg/database:master
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_USER=${DB_USERNAME}
      - SERVICE_TAGS=dev
      - SERVICE_NAME=database
    deploy:
      replicas: 1
      update_config:
        parallelism: 0
        failure_action: rollback
        delay: 5s
      rollback_config:
        parallelism: 0
      restart_policy:
        condition: on-failure
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
  backend:
    image: docker.io/pbbg/backend:master
    deploy:
      replicas: 1
      update_config:
        parallelism: 0
        failure_action: rollback
        delay: 5s
      rollback_config:
        parallelism: 0
      restart_policy:
        condition: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/tests"]
  frontend:
    image: docker.io/pbbg/frontend:master
    deploy:
      replicas: 1
      update_config:
        parallelism: 0
        failure_action: rollback
        delay: 5s
      rollback_config:
        parallelism: 0
      restart_policy:
        condition: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
  proxy:
    image: docker.io/pbbg/proxy:master
    ports:
      - 80:80
    volumes:
      - /root/certs-data/:/data/letsencrypt/
    deploy:
      replicas: 1
      update_config:
        parallelism: 0
        failure_action: rollback
        delay: 5s
      rollback_config:
        parallelism: 0
      restart_policy:
        condition: on-failure
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost"]
