version: "3.8"
services:
  database:
    image: docker.io/pbbg/database:master
    container_name: database
    restart: on-failure
  backend:
    image: docker.io/pbbg/backend:master
    container_name: backend
    restart: on-failure
    depends_on:
      - database
  frontend:
    image: docker.io/pbbg/frontend:master
    container_name: frontend
    restart: on-failure
    depends_on:
      - database
      - backend
  proxy:
    image: docker.io/pbbg/proxy:master
    container_name: proxy
    restart: on-failure
    ports:
      - 80:80
    depends_on:
      - database
      - backend
      - frontend
