version: "3.8"
networks:
  pbbg:
    driver: bridge
services:
  database:
    build:
      context: ./database
      dockerfile: Dockerfile
    container_name: database
    networks:
      - pbbg
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_USER=${DB_USERNAME}
      - SERVICE_TAGS=dev
      - SERVICE_NAME=database
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    environment:
      - APP_URL=${APP_URL}
      - APP_NAME=${APP_NAME}
      - APP_KEY=${APP_KEY}
      - LOG_CHANNEL=${LOG_CHANNEL}
      - DB_CONNECTION=${DB_CONNECTION}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - APP_ENV=dev
      - APP_DEBUG=true
    networks:
      - pbbg
    depends_on:
      - database
    volumes:
      - .:/workspace:cached
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    networks:
      - pbbg
    depends_on:
      - database
      - backend
    volumes:
      - .:/workspace:cached
  proxy:
    build:
      context: ./proxy/local
      dockerfile: Dockerfile
    container_name: proxy
    networks:
      - pbbg
    depends_on:
      - database
      - backend
      - frontend
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./proxy/local:/etc/nginx/conf.d
