version: "3.8"
services:
  database:
    build:
      context: ./database
      dockerfile: Dockerfile
    image: docker.io/pbbg/database:master
    container_name: database
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_USER=${DB_USERNAME}
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: docker.io/pbbg/backend:master
    container_name: backend
    environment:
      - APP_URL=${APP_URL}
      - APP_NAME=${APP_NAME}
      - APP_KEY=${APP_KEY}
      - LOG_CHANNEL=${LOG_CHANNEL}
      - DB_CONNECTION=${DB_CONNECTION}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - APP_ENV=prod
      - APP_DEBUG=false
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: docker.io/pbbg/frontend:master
    container_name: frontend
  proxy:
    build:
      context: ./proxy/prod
      dockerfile: Dockerfile
    image: docker.io/pbbg/proxy:master
    container_name: proxy
    ports:
      - 80:80
