name: PBBG Production Build
# Should only run for new Tags on the Release branch are pushed to the repository
on:
  push:
    branches:
      - "release"
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build production images
        env:
          APP_NAME: ${{secrets.APP_NAME}}
          APP_ENV: ${{secrets.APP_ENV}}
          APP_KEY: ${{secrets.APP_KEY}}
          APP_DEBUG: ${{secrets.APP_DEBUG}}
          APP_URL: ${{secrets.APP_URL}}
          LOG_CHANNEL: ${{secrets.LOG_CHANNEL}}
          DB_CONNECTION: ${{secrets.DB_CONNECTION}}
          DB_HOST: ${{secrets.DB_HOST}}
          DB_PORT: ${{secrets.DB_PORT}}
          DB_DATABASE: ${{secrets.DB_DATABASE}}
          DB_USERNAME: ${{secrets.DB_USERNAME}}
          DB_PASSWORD: ${{secrets.DB_PASSWORD}}
          BROADCAST_DRIVER: ${{secrets.BROADCAST_DRIVER}}
          CACHE_DRIVER: ${{secrets.CACHE_DRIVER}}
          QUEUE_CONNECTION: ${{secrets.QUEUE_CONNECTION}}
          SESSION_DRIVER: ${{secrets.SESSION_DRIVER}}
          SESSION_LIFETIME: ${{secrets.SESSION_LIFETIME}}
          MAIL_DRIVER: ${{secrets.MAIL_DRIVER}}
          MAIL_HOST: ${{secrets.MAIL_HOST}}
          MAIL_PORT: ${{secrets.MAIL_PORT}}
        run: |
          chmod 755 ./scripts/build-images.sh; ./scripts/build-images.sh production
      - name: Push images to Docker Hub
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          chmod 755 ./scripts/push-images.sh; ./scripts/push-images.sh --username=${{secrets.DOCKER_USER}} --password=${{secrets.DOCKER_PASSWORD}} --production=true
      - name: Update Portainer Stack in Production
          env:
            PORTAINER_USER: ${{secrets.PORTAINER_USER}}
            PORTAINER_PASSWORD: ${{secrets.PORTAINER_PASSWORD}}
          run: |
            chmod 755 ./scripts/update-portainer-stack.sh; ./scripts/update-portainer-stack.sh --portainer_username=${{secrets.PORTAINER_USER}} --portainer_password=${{secrets.PORTAINER_PASSWORD}} --production=true
